var _colignyErrors = {
  "argNotSpecified":new Error ("Missing arguments."),
  "wrongParamType":new Error ("Argument(s) of wrong data type."),
  "invalidMonth":new Error ("Invalid Month number specified."),
  "invalidDays":new Error("Days specified outside possible day range."),
  "invalidCycles":new Error("Cannot compare dates of different cycle types.")
}

function colignyMonth(name, days) {
  if (typeof (name || days) == 'undefined') {
    throw _colignyErrors["argNotSpecified"];
  } else if (typeof name != "string" || typeof days != "number") {
    throw _colignyErrors["wrongParamType"];
  }

  this.name = name;
  this.days = days;
  this.index = 0;
}

function colignyYear(year, metonic) {
  if (typeof year != "number") {
    throw _colignyErrors["wrongParamType"];
  } else if (typeof metonic == "undefined") {
    metonic = false;
  }

  this.metonic = metonic;
  this.year = year;
  this.months = [
    new colignyMonth("Samonios", 30),
    new colignyMonth("Dumanios", 29),
    new colignyMonth("Riuros", 30),
    new colignyMonth("Anagantios", 29),
    new colignyMonth("Ogronios", 30),
    new colignyMonth("Cutios", 30),
    new colignyMonth("Giamonios", 29),
    new colignyMonth("Simiuisonna", 30),
    new colignyMonth("Elembi", 29),
    new colignyMonth("Aedrinni", 30),
    new colignyMonth("Cantlos", 29)
  ];

  var metMap = {
    '-0':2,
    '-18':3,
    '-17':4,
    '-16':5,
    '-15':1,
    '-14':2,
    '-13':3,
    '-12':4,
    '-11':5,
    '-10':1,
    '-9':2,
    '-8':3,
    '-7':4,
    '-6':5,
    '-5':1,
    '-4':2,
    '-3':3,
    '-2':4,
    '-1':5,
    0:2,
    1:3,
    2:4,
    3:5,
    4:1,
    5:2,
    6:3,
    7:4,
    8:5,
    9:1,
    10:2,
    11:3,
    12:4,
    13:5,
    14:1,
    15:2,
    16:3,
    17:4,
    18:5
  }

  var satMap = {
    '-0':1,
    '-4':2,
    '-3':3,
    '-2':4,
    '-1':5,
    0:1,
    1:2,
    2:3,
    3:4,
    4:5
  }

  if (this.metonic) {
    this.ident = metMap[(this.year - 4999) % 19];
  } else {
    this.ident = satMap[(this.year - 4998) % 5];
  }

  
  switch (this.ident) {
    case 1:
      this.months.splice(0, 0, new colignyMonth("Quimonios", 29));
      this.months.splice(8, 0, new colignyMonth("Equos", 30));
      break;
    case 3:
      this.months.splice(8, 0, new colignyMonth("Equos", 29));
      if (this.year - 4998 % 30 !== (27 || -3) || (this.metonic)) {
        this.months.splice(6, 0, new colignyMonth("Rantaranos", 30));
      }
      break;
    case 5:
      this.months.splice(8, 0, new colignyMonth("Equos", 30));
      break;
    default:
      this.months.splice(8, 0, new colignyMonth("Equos", 29));
      break;
  }

  if (this.metonic) {
    if (Math.abs(this.year - 4999) >= 60.97 &&
        Math.abs(this.year - 4999) % 60.97 <= 5 &&
        ident === 5) {
      this.fullYear.months[8].days = 29;
    }

    if (Math.abs(this.year - 4999) > 6568.62 &&
        Math.abs(this.year - 4999) % 6568.62 <= 5 &&
        ident === 3) {
      this.fullYear.months.splice(6, 1);
    } 
  } else {
    if (Math.abs(this.year - 4998) >= 197.97 &&
        Math.abs(this.year - 4998) % 197.97 <= 5 &&
        ident === 5) {
      this.fullYear.months[8].days = 29;
    }

    if (Math.abs(this.year - 4998) > 635.04 &&
        Math.abs(this.year - 4998) % 635.04 <= 30 &&
        this.year - 4998 % 30 === (27 || -3)) {
      this.fullYear.months.splice(6, 0, new colignyMonth("Rantaranos", 30));
    }
  }

  this.yearDays = 0;

  for (i = 0; i < this.months.length; i++) {
    this.months[i].index = i;
    this.yearDays += this.months[i].days;
  }
}

function colignyDate(year, month, day, metonic) {
  if (typeof (year || month || day) != "number") {
    throw _colignyErrors["wrongParamType"];
  } else if (typeof metonic == "undefined") {
    metonic = false;
  }

  this.metonic = metonic;
  this.year = year;
  this.day = day;
  this.fullYear = new colignyYear(year, metonic);
  if (month >= this.fullYear.months.length || month < 0) {
    throw _colignyErrors["invalidMonth"];
  } else {
    this.month = this.fullYear.months[month];
  }

  this.yearToBegin = 0;

  for (var i = 0; i <= this.month.index; i++) {
    if (i === this.month.index) {
      this.yearToBegin += this.day;
    } else {
      this.yearToBegin += this.fullYear.months[i].days;
    }
  }

  this.yearToEnd = this.fullYear.yearDays - this.yearToBegin;
}

colignyDate.prototype.string = function(cyc) {
  if (typeof cyc == "undefined") {
    cyc = false;
  }

  if (cyc) {
    return this.month.name + " " + this.day + " " + this.fullYear.ident;
  } else {
    return this.month.name + " " + this.day + ", " + this.year;
  }
}

colignyDate.prototype.inscription = function() {
  var inscrips = {
    "Quimonios 1 1":["MD SIMIUIS GIAMONI", "IVOS"],
    "Quimonios 2 1":["MD SIMIUISONNA", "IVOS"],
    "Quimonios 3 1":["MD SIMIUIS EQUI", "IVOS"],
    "Quimonios 4 1":["D ELEMBI"],
    "Quimonios 5 1":["D EDRINNI AMB"],
    "Quimonios 6 1":["D CANTLOS"],
    "Quimonios 7 1":["MD PRINI LOUD SAMONI","TINA D[---","NE[---","?I[---"],
    "Quimonios 8 1":["D SAMON DUMANI", "M[---"],
    "Quimonios 9 1":["MD DUMAN RIVRI", "EDVTIO[---", "MV[---"],
    "Quimonios 10 1":["D ANAGANT"],
    "Quimonios 11 1":["(IIT) D AMB OGRON"],
    "Quimonios 12 1":["(IIT) MD CUTIOS"],
    "Quimonios 13 1":["(TII) D GIAMON"],
    "Quimonios 14 1":["NSDS/D EQVI SIMIUIS"],
    "Quimonios 15 1":["MD SIMIUIS EQVI"],
    "Quimonios 16 1":["MD EDRINI ELEMB"],
    "Quimonios 17 1":["D ELEMB EDRINI"],
    "Quimonios 18 1":["(IIT) D CANTLI AMB RIXRI"],
    "Quimonios 19 1":["(TII) MD SAMON"],
    "Quimonios 20 1":["D DUMANNI AMB ?RI"],
    "Quimonios 21 1":["IIT MD RIVRI"],
    "Quimonios 22 1":["NSDS SAMONI ANAGAN", "INNIS R [----]TIT"],
    "Quimonios 23 1":["NSDS SAM OGRON QVTIO", "INNIS R"],
    "Quimonios 24 1":["N(SDS) SAM QVTIO INNIS R", "ED[----", "SV[----"],
    "Quimonios 25 1":["(TII) D GIAMON"],
    "Quimonios 26 1":["D AMB SIMIUS", "IVOS"],
    "Quimonios 27 1":["(ITI) D EQVI", "IVOS"],
    "Quimonios 28 1":["(ITI) D AMB ELEMB", "IVOS"],
    "Quimonios 29 1":["MD EDRINNI", "IVOS"],
    "Samonios 1 1":["D DUMANNI", "IVOS"],
    "Samonios 2 1":["MD", "IVOS"],
    "Samonios 3 1":["TII D EXINGI DUM", "IVOS"],
    "Samonios 4 1":["MD", "IVOS"],
    "Samonios 5 1":["D AMB * RIX * RI"],
    "Samonios 6 1":["MD"],
    "Samonios 7 1":["N DUMAN INIS R"],
    "Samonios 8 1":["MD SAMONI"],
    "Samonios 9 1":["D DUMANI"],
    "Samonios 10 1":["MD"],
    "Samonios 11 1":["D AMB"],
    "Samonios 12 1":["MD [D M]"],
    "Samonios 13 1":["MD [D M]"],
    "Samonios 14 1":["MD [D M]"],
    "Samonios 15 1":["MD [D M]"],
    "Samonios 16 1":["D DUMANNI"],
    "Samonios 17 1":["MD TRINO SAM SINDIV", "(IVOS)"],
    "Samonios 18 1":["D AMB"],
    "Samonios 19 1":["MD"],
    "Samonios 20 1":["D AMB"],
    "Samonios 21 1":["IIT MD"],
    "Samonios 22 1":["D DUMANI AMB"],
    "Samonios 23 1":["TII D DUMANI"],
    "Samonios 24 1":["N DUM INIS R"],
    "Samonios 25 1":["MD"],
    "Samonios 26 1":["D AMB"],
    "Samonios 27 1":["MD"],
    "Samonios 28 1":["D AMB"],
    "Samonios 29 1":["MD"],
    "Samonios 30 1":["D AMB"],
    "Dumanios 1 1":["SAMON PRINI LOUD"],
    "Dumanios 2 1":["D"],
    "Dumanios 3 1":["D"],
    "Dumanios 4 1":["D"],
    "Dumanios 5 1":["PRINI LAG AMB"],
    "Dumanios 6 1":["ITI D"],
    "Dumanios 7 1":["MD RIVRI"],
    "Dumanios 8 1":["MD RIVRI"],
    "Dumanios 9 1":["MD RIVRI"],
    "Dumanios 10 1":["D"],
    "Dumanios 11 1":["N INIS R"],
    "Dumanios 12 1":["ITI D"],
    "Dumanios 13 1":["IIT D", "IVOS"],
    "Dumanios 14 1":["D", "IVOS"],
    "Dumanios 15 1":["D", "IVOS"],
    "Dumanios 16 1":["MD SAMONI", "IVOS"],
    "Dumanios 17 1":["MD SAMONI", "IVOS"],
    "Dumanios 18 1":["ITI D AMB", "IVOS"],
    "Dumanios 19 1":["IIT D", "IVOS"],
    "Dumanios 20 1":["D AMB", "IVOS"],
    "Dumanios 21 1":["IIT D"],
    "Dumanios 22 1":["D RIVRI AMB"],
    "Dumanios 23 1":["D PETIUX RIV ANAG"],
    "Dumanios 24 1":["D AMB RIVRI"],
    "Dumanios 25 1":["IIT D"],
    "Dumanios 26 1":["D AMB", "[IVOS]"],
    "Dumanios 27 1":["N INIS R", "[IVOS]"],
    "Dumanios 28 1":["D AMB", "IVOS"],
    "Dumanios 29 1":["NSDS", "IVOS"],
    "Riuros 1 1":["D ANAGANT EXO", "IVOS"],
    "Riuros 2 1":["PRINI LOUD", "IVOS"],
    "Riuros 3 1":["MD", "IVOS"],
    "Riuros 4 1":["(MD) BRIGIOMU RIVRI"],
    "Riuros 5 1":["N INIS R"],
    "Riuros 6 1":["MD"],
    "Riuros 7 1":["ITI D ANAGANT"],
    "Riuros 8 1":["IIT D ANAGANT"],
    "Riuros 9 1":["D ANAGANT"],
    "Riuros 10 1":["MD"],
    "Riuros 11 1":["N INIS R"],
    "Riuros 12 1":["MD"],
    "Riuros 13 1":["DEC/VOR LUG RIVRI"],
    "Riuros 14 1":["MD"],
    "Riuros 15 1":["MD"],
    "Riuros 16 1":["MD"],
    "Riuros 17 1":["MD"],
    "Riuros 18 1":["D AMB"],
    "Riuros 19 1":["MD"],
    "Riuros 20 1":["D AMB"],
    "Riuros 21 1":["IIT MD"],
    "Riuros 22 1":["N ANAG INIS R"],
    "Riuros 23 1":["D ANAG"],
    "Riuros 24 1":["N ANAG INIS R"],
    "Riuros 25 1":["MD PETIUX RIVRI"],
    "Riuros 26 1":["D AMB"],
    "Riuros 27 1":["MD"],
    "Riuros 28 1":["D AMB"],
    "Riuros 29 1":["MD"],
    "Riuros 30 1":["D AMB"],
    "Anagantios 1 1":["MD RIVRI"],
    "Anagantios 2 1":["D"],
    "Anagantios 3 1":["D"],
    "Anagantios 4 1":["MD OGIOUMU RIVRI"],
    "Anagantios 5 1":["N INIS R"],
    "Anagantios 6 1":["PRINI LAG"],
    "Anagantios 7 1":["MD OGRONI"],
    "Anagantios 8 1":["MD OGRONI"],
    "Anagantios 9 1":["MD OGRONI"],
    "Anagantios 10 1":["D"],
    "Anagantios 11 1":["D AMB"],
    "Anagantios 12 1":["TII D"],
    "Anagantios 13 1":["ITI D"],
    "Anagantios 14 1":["IIT D"],
    "Samonios 1 2":["N DUMANNI", "IVOS"],
    "Samonios 2 2":["ITI MD", "IVOS"],
    "Samonios 3 2":["TII D DUM ALE", "IVOS"],
    "Samonios 4 2":["MD"],
    "Samonios 5 2":["D AMB"],
    "Samonios 6 2":["MD"],
    "Samonios 7 2":["PRINI LOUDIN"],
    "Samonios 8 2":["D DUMANI"],
    "Samonios 9 2":["IIT MD"],
    "Samonios 10 2":["MD"],
    "Samonios 11 2":["D AMB"],
    "Samonios 12 2":["MD"],
    "Samonios 13 2":["TII MD"],
    "Samonios 14 2":["ITI MD"],
    "Samonios 15 2":["IIT MD"],
    "Samonios 16 2":["D DUMANNI"],
    "Samonios 17 2":["IIT MD TRINUX SAM"],
    "Samonios 18 2":["D AMB"],
    "Samonios 19 2":["TII MD"],
    "Samonios 20 2":["ITI D AMB"],
    "Samonios 21 2":["IIT MD"],
    "Samonios 22 2":["D AMB"],
    "Samonios 23 2":["N INIS R"],
    "Samonios 24 2":["N INIS R"],
    "Samonios 25 2":["TII MD"],
    "Samonios 26 2":["ITI D AMB", "IVOS"],
    "Samonios 27 2":["IIT MD", "IVOS"],
    "Samonios 28 2":["D AMB", "IVOS"],
    "Samonios 29 2":["MD", "IVOS"],
    "Samonios 30 2":["D AMB", "IVOS"],
    "Dumanios 1 2":["SAM PRINI LOUD EXO", "IVOS"],
    "Dumanios 2 2":["N", "IVOS"],
    "Dumanios 3 2":["D", "IVOS"],
    "Dumanios 4 2":["D", "IVOS"],
    "Dumanios 5 2":["PRINI LAGET"],
    "Dumanios 6 2":["D"],
    "Dumanios 7 2":["N INIS R"],
    "Dumanios 8 2":["ITI MD SAMONI"],
    "Dumanios 9 2":["D"],
    "Dumanios 10 2":["D"],
    "Dumanios 11 2":["N INIS R"],
    "Dumanios 12 2":["D"],
    "Dumanios 13 2":["D"],
    "Dumanios 14 2":["D"],
    "Dumanios 15 2":["D"],
    "Dumanios 16 2":["MD SAMONI"],
    "Dumanios 17 2":["MD SAMONI"],
    "Dumanios 18 2":["ITI D AMB"],
    "Dumanios 19 2":["IIT D"],
    "Dumanios 20 2":["D AMB"],
    "Dumanios 21 2":["IIT M D"],
    "Dumanios 22 2":["D AMB"],
    "Dumanios 23 2":["TII D"],
    "Dumanios 24 2":["N INIS R"],
    "Dumanios 25 2":["IIT D"],
    "Dumanios 26 2":["D AMB"],
    "Dumanios 27 2":["N INIS R"],
    "Dumanios 28 2":["D AMB"],
    "Dumanios 29 2":["NSDS"],
    "Riuros 1 2":["D ANAGANT"],
    "Riuros 2 2":["PRINI LOUD"],
    "Riuros 3 2":["N"],
    "Riuros 4 2":["(MD) BRIGIOMU RIVRI"],
    "Riuros 5 2":["N INIS R"],
    "Riuros 6 2":["MD"],
    "Riuros 7 2":["MD"],
    "Riuros 8 2":["PRINI LOUD"],
    "Riuros 9 2":["ITI MD"],
    "Riuros 10 2":["IIT MD"],
    "Riuros 11 2":["N INIS R"],
    "Riuros 12 2":["MD"],
    "Riuros 13 2":["DEC/VOR LUG RIV"],
    "Riuros 14 2":["NSDS", "IVOS"],
    "Riuros 15 2":["DSNS", "IVOS"],
    "Riuros 16 2":["MD", "IVOS"],
    "Riuros 17 2":["MD", "IVOS"],
    "Riuros 18 2":["D AMB", "IVOS"],
    "Riuros 19 2":["MD", "IVOS"],
    "Riuros 20 2":["TII D AMB", "IVOS"],
    "Riuros 21 2":["ITT MD"],
    "Riuros 22 2":["IIT D AMB"],
    "Riuros 23 2":["D PETIUX ANAG"],
    "Riuros 24 2":["D AMB"],
    "Riuros 25 2":["IIT MD PETIUX RIVRI"],
    "Riuros 26 2":["TII D AMB", "IVOS"],
    "Riuros 27 2":["ITI MD", "IVOS"],
    "Riuros 28 2":["IIT D AMB", "IVOS"],
    "Riuros 29 2":["MD", "IVOS"],
    "Riuros 30 2":["D AMB", "IVOS"],
    "Anagantios 1 2":["MD RIVRI IX", "IVOS"],
    "Anagantios 2 2":["D", "IVOS"],
    "Anagantios 3 2":["D", "IVOS"],
    "Anagantios 4 2":["N OGIOUMU RIVRI"],
    "Anagantios 5 2":["N INIS R"],
    "Anagantios 6 2":["PRINI LAG"],
    "Anagantios 7 2":["D"],
    "Anagantios 8 2":["D"],
    "Anagantios 9 2":["D"],
    "Anagantios 10 2":["D"],
    "Anagantios 11 2":["D AMB"],
    "Anagantios 12 2":["D"],
    "Anagantios 13 2":["D"],
    "Anagantios 14 2":["D"],
    "Anagantios 15 2":["D"],
    "Anagantios 16 2":["D"],
    "Anagantios 17 2":["D"],
    "Anagantios 18 2":["TII D AMB"],
    "Anagantios 19 2":["ITI D"],
    "Anagantios 20 2":["IIT D AMB"],
    "Anagantios 21 2":["N INIS R"],
    "Anagantios 22 2":["N INIS R"],
    "Anagantios 23 2":["D"],
    "Anagantios 24 2":["N INIS R"],
    "Anagantios 25 2":["ITI D"],
    "Anagantios 26 2":["IIT D AMB"],
    "Anagantios 27 2":["D"],
    "Anagantios 28 2":["D AMB"],
    "Anagantios 29 2":["D"],
    "Ogronios 1 2":["MD"],
    "Ogronios 2 2":["MD"],
    "Ogronios 3 2":["PRINI LOUD"],
    "Ogronios 4 2":["ITI MD"],
    "Ogronios 5 2":["N INIS R"],
    "Ogronios 6 2":["MD"],
    "Ogronios 7 2":["MD"],
    "Ogronios 8 2":["MD"],
    "Ogronios 9 2":["TII MD"],
    "Ogronios 10 2":["ITI MD"],
    "Ogronios 11 2":["IIT D AMB"],
    "Ogronios 12 2":["MD"],
    "Ogronios 13 2":["MD"],
    "Ogronios 14 2":["MD"],
    "Ogronios 15 2":["N"],
    "Ogronios 16 2":["TII MD CVTI"],
    "Ogronios 17 2":["ITI MD CVTI"],
    "Ogronios 18 2":["IIT D CVTI AMB"],
    "Ogronios 19 2":["MD"],
    "Ogronios 20 2":["D AMB"],
    "Ogronios 21 2":["TIT MD"],
    "Ogronios 22 2":["ITI D AMB"],
    "Ogronios 23 2":["ITI MD QVTI"],
    "Ogronios 24 2":["D AMB"],
    "Ogronios 25 2":["MD"],
    "Ogronios 26 2":["D AMB"],
    "Ogronios 27 2":["N INIS R"],
    "Ogronios 28 2":["ITI D AMB"],
    "Ogronios 29 2":["IIT MD"],
    "Ogronios 30 2":["D AMB"],
    "Cutios 1 2":["MD"],
    "Cutios 2 2":["MD"],
    "Cutios 3 2":["MD"],
    "Cutios 4 2":["PRINI LOUD"],
    "Cutios 5 2":["N INIS R"],
    "Cutios 6 2":["N"],
    "Cutios 7 2":["MD"],
    "Cutios 8 2":["MD"],
    "Cutios 9 2":["N INIS R"],
    "Cutios 10 2":["TII MD"],
    "Cutios 11 2":["ITI D AMB"],
    "Cutios 12 2":["IIT MD"],
    "Cutios 13 2":["MD"],
    "Cutios 14 2":["MD"],
    "Cutios 15 2":["MD"],
    "Cutios 16 2":["MD OGRON"],
    "Cutios 17 2":["MD OGRON"],
    "Cutios 18 2":["D OGRON AMB"],
    "Cutios 19 2":["N INIS R"],
    "Cutios 20 2":["D AMB"],
    "Cutios 21 2":["N INIS R"],
    "Cutios 22 2":["TII D AMB"],
    "Cutios 23 2":["IIT MD OGRONI"],
    "Cutios 24 2":["IIT D AMB"],
    "Cutios 25 2":["MD"],
    "Cutios 26 2":["D AMB"],
    "Cutios 27 2":["MD"],
    "Cutios 28 2":["TII D AMB", "IVOS"],
    "Cutios 29 2":["ITI MD", "IVOS"],
    "Cutios 30 2":["IIT D AMB", "IVOS"],
    "Giamonios 1 2":["MD SIMUISONNA EXO", "IVOS"],
    "Giamonios 2 2":["D", "IVOS"],
    "Giamonios 3 2":["D", "IVOS"],
    "Giamonios 4 2":["D"],
    "Giamonios 5 2":["D AMB"],
    "Giamonios 6 2":["D"],
    "Giamonios 7 2":["N PRINI LAG"],
    "Giamonios 8 2":["D"],
    "Giamonios 9 2":["N INIS R"],
    "Giamonios 10 2":["D"],
    "Giamonios 11 2":["D AMB"],
    "Giamonios 12 2":["D"],
    "Giamonios 13 2":["TII D"],
    "Giamonios 14 2":["ITI D"],
    "Giamonios 15 2":["IIT D"],
    "Giamonios 16 2":["D"],
    "Giamonios 17 2":["NSDS"],
    "Giamonios 18 2":["D AMB"],
    "Giamonios 19 2":["TII D"],
    "Giamonios 20 2":["ITI D AMB"],
    "Giamonios 21 2":["IIT D"],
    "Giamonios 22 2":["N INIS R"],
    "Giamonios 23 2":["N INIS R"],
    "Giamonios 24 2":["D AMB"],
    "Giamonios 25 2":["TII D"],
    "Giamonios 26 2":["N INIS R"],
    "Giamonios 27 2":["IIT D"],
    "Giamonios 28 2":["D AMB"],
    "Giamonios 29 2":["D"],
    "Simiuisonna 1 2":["GIAM PRINI LAG"],
    "Simiuisonna 2 2":["MD"],
    "Simiuisonna 3 2":["D EQVI"],
    "Simiuisonna 4 2":["MD"],
    "Simiuisonna 5 2":["N INIS R"],
    "Simiuisonna 6 2":["D EQVI"],
    "Simiuisonna 7 2":["IIT MD TIOCOBREXTIO"],
    "Simiuisonna 8 2":["N"],
    "Simiuisonna 9 2":["MD SINDIU", "IVOS"],
    "Simiuisonna 10 2":["MD"],
    "Simiuisonna 11 2":["TII D AMB"],
    "Simiuisonna 12 2":["ITI MD"],
    "Simiuisonna 13 2":["D EQVI"],
    "Simiuisonna 14 2":["D EQVI"],
    "Simiuisonna 15 2":["D EQVI"],
    "Simiuisonna 16 2":["D EQVI"],
    "Simiuisonna 17 2":["D EQVI"],
    "Simiuisonna 18 2":["D AMB EQVI"],
    "Simiuisonna 19 2":["IIT MD"],
    "Simiuisonna 20 2":["D AMB"],
    "Simiuisonna 21 2":["IIT D EQVI"],
    "Simiuisonna 22 2":["D AMB"],
    "Simiuisonna 23 2":["TII MD"],
    "Simiuisonna 24 2":["ITI D AMB"],
    "Simiuisonna 25 2":["IIT MD"],
    "Simiuisonna 26 2":["D AMB"],
    "Simiuisonna 27 2":["MD"],
    "Simiuisonna 28 2":["D AMB"],
    "Simiuisonna 29 2":["NSDS (AMB)"],
    "Simiuisonna 30 2":["DSNS AMB"],
    "Equos 1 2":["D"],
    "Equos 2 2":["PRINI LAG"],
    "Equos 3 2":["MD SINIVIS"],
    "Equos 4 2":["D"],
    "Equos 5 2":["D AMB"],
    "Equos 6 2":["ITI MD SIMIVISO"],
    "Equos 7 2":["D"],
    "Equos 8 2":["PRINI LAG"],
    "Equos 9 2":["N"],
    "Equos 10 2":["D"],
    "Equos 11 2":["D AMB"],
    "Equos 12 2":["D"],
    "Equos 13 2":["IIT MD SIMI"],
    "Equos 14 2":["MD SIMI"],
    "Equos 15 2":["MD SIMI"],
    "Equos 16 2":["MD SIMIVIS"],
    "Equos 17 2":["TII MD SIMIVIS"],
    "Equos 18 2":["ITI D AMB SIMIVIS"],
    "Equos 19 2":["D"],
    "Equos 20 2":["TII D AMB"],
    "Equos 21 2":["IIT (M)D SIMIVIS"],
    "Equos 22 2":["D AMB"],
    "Equos 23 2":["D"],
    "Equos 24 2":["D AMB"],
    "Equos 25 2":["D"],
    "Equos 26 2":["TII D AMB", "IVOS"],
    "Equos 27 2":["ITI D", "IVOS"],
    "Equos 28 2":["IIT D AMB", "IVOS"],
    "Equos 29 2":["D", "IVOS"],
    "Elembi 1 2":["D", "IVOS"],
    "Elembi 2 2":["D", "IVOS"],
    "Elembi 3 2":["PRINI LAG", "IVOS"],
    "Elembi 4 2":["D", "IVOS"],
    "Elembi 5 2":["D AMB"],
    "Elembi 6 2":["D"],
    "Elembi 7 2":["D"],
    "Elembi 8 2":["D"],
    "Elembi 9 2":["PRINI LAG"],
    "Elembi 10 2":["N INIS R"],
    "Elembi 11 2":["D AMB"],
    "Elembi 12 2":["D"],
    "Elembi 13 2":["D"],
    "Elembi 14 2":["D"],
    "Elembi 15 2":["(N)"],
    "Elembi 16 2":["MD EDRIN"],
    "Elembi 17 2":["MD EDRIN"],
    "Elembi 18 2":["TII D EDRIN AMB"],
    "Elembi 19 2":["D"],
    "Elembi 20 2":["D AMB"],
    "Elembi 21 2":["IIT D"],
    "Elembi 22 2":["D AMB"],
    "Elembi 23 2":["D"],
    "Elembi 24 2":["D AMB"],
    "Elembi 25 2":["D"],
    "Elembi 26 2":["D AMB"],
    "Elembi 27 2":["TII D"],
    "Elembi 28 2":["ITI D AMB"],
    "Elembi 29 2":["IIT D"],
    "Aedrinni 1 2":["D CANTLI", "IVOS"],
    "Aedrinni 2 2":["MD", "IVOS"],
    "Aedrinni 3 2":["MD", "IVOS"],
    "Aedrinni 4 2":["MD"],
    "Aedrinni 5 2":["D AMB"],
    "Aedrinni 6 2":["PRINI LOUD"],
    "Aedrinni 7 2":["ITI MD TIOGBR?"],
    "Aedrinni 8 2":["IIT MD TIOCOBREXTIO"],
    "Aedrinni 9 2":["MD"],
    "Aedrinni 10 2":["MD"],
    "Aedrinni 11 2":["N"],
    "Aedrinni 12 2":["TII MD"],
    "Aedrinni 13 2":["ITI MD"],
    "Aedrinni 14 2":["IIT MD"],
    "Aedrinni 15 2":["MD"],
    "Aedrinni 16 2":["D ELEMB"],
    "Aedrinni 17 2":["D ELEMB"],
    "Aedrinni 18 2":["D ELEMB AMB"],
    "Aedrinni 19 2":["ITI MD"],
    "Aedrinni 20 2":["IIT D AMB"],
    "Aedrinni 21 2":["IIT MD"],
    "Aedrinni 22 2":["D AMB"],
    "Aedrinni 23 2":["MD"],
    "Aedrinni 24 2":["TII D AMB"],
    "Aedrinni 25 2":["ITI D SINDIV", "IVOS"],
    "Aedrinni 26 2":["IIT D AMB"],
    "Aedrinni 27 2":["MD"],
    "Aedrinni 28 2":["D AMB"],
    "Aedrinni 29 2":["MD"],
    "Aedrinni 30 2":["N"],
    "Cantlos 1 2":["MD AEDRIN"],
    "Cantlos 2 2":["D"],
    "Cantlos 3 2":["D"],
    "Cantlos 4 2":["PRINI LAG"],
    "Cantlos 5 2":["D AMB"],
    "Cantlos 6 2":["D"],
    "Cantlos 7 2":["D"],
    "Cantlos 8 2":["D"],
    "Cantlos 9 2":["D"],
    "Cantlos 10 2":["D"],
    "Cantlos 11 2":["D AMB"],
    "Cantlos 12 2":["N"],
    "Cantlos 13 2":["D"],
    "Cantlos 14 2":["D"],
    "Cantlos 15 2":["D TIOCOBREXTIO"],
    "Cantlos 16 2":["D"],
    "Cantlos 17 2":["D"],
    "Cantlos 18 2":["D AMB"],
    "Cantlos 19 2":["N INIS R"],
    "Cantlos 20 2":["D AMB"],
    "Cantlos 21 2":["IIT D"],
    "Cantlos 22 2":["D AMB"],
    "Cantlos 23 2":["D"],
    "Cantlos 24 2":["D AMB"],
    "Cantlos 25 2":["D"],
    "Cantlos 26 2":["D AMB"],
    "Cantlos 27 2":["D"],
    "Cantlos 28 2":["TII D AMB", "IVOS"],
    "Cantlos 29 2":["ITI D", "IVOS"],
    "Samonios 1 3":["N DUMANNI", "IVOS"],
    "Samonios 2 3":["ITI MD", "IVOS"],
    "Samonios 3 3":["TII D DUM ALE", "IVOS"],
    "Samonios 4 3":["MD"],
    "Samonios 5 3":["D AMB"],
    "Samonios 6 3":["MD"],
    "Samonios 7 3":["PRINI LOUDIN"],
    "Samonios 8 3":["D DUMANI"],
    "Samonios 9 3":["IIT MD"],
    "Samonios 10 3":["MD"],
    "Samonios 11 3":["D AMB"],
    "Samonios 12 3":["MD"],
    "Samonios 13 3":["N"],
    "Samonios 14 3":["ITI MD"],
    "Samonios 15 3":["IIT MD"],
    "Samonios 16 3":["D DUMANNI"],
    "Samonios 17 3":["IIT MD TRINUX SAM"],
    "Samonios 18 3":["D AMB"],
    "Samonios 19 3":["TII MD"],
    "Samonios 20 3":["ITI D AMB"],
    "Samonios 21 3":["IIT MD"],
    "Samonios 22 3":["D AMB"],
    "Samonios 23 3":["N INIS R"],
    "Samonios 24 3":["N INIS R"],
    "Samonios 25 3":["TII MD"],
    "Samonios 26 3":["ITI D AMB", "IVOS"],
    "Samonios 27 3":["IIT MD", "IVOS"],
    "Samonios 28 3":["D AMB", "IVOS"],
    "Samonios 29 3":["MD", "IVOS"],
    "Samonios 30 3":["D AMB", "IVOS"],
    "Dumanios 1 3":["SAM PRINI LOUD EXO", "IVOS"],
    "Dumanios 2 3":["N", "IVOS"],
    "Dumanios 3 3":["D", "IVOS"],
    "Dumanios 4 3":["D", "IVOS"],
    "Dumanios 5 3":["PRINI LAGET"],
    "Dumanios 6 3":["D"],
    "Dumanios 7 3":["N INIS R"],
    "Dumanios 8 3":["ITI MD SAMONI"],
    "Dumanios 9 3":["D"],
    "Dumanios 10 3":["D"],
    "Dumanios 11 3":["N INIS R"],
    "Dumanios 12 3":["D"],
    "Dumanios 13 3":["D"],
    "Dumanios 14 3":["N"],
    "Dumanios 15 3":["D"],
    "Dumanios 16 3":["MD SAMONI"],
    "Dumanios 17 3":["MD SAMONI"],
    "Dumanios 18 3":["D AMB"],
    "Dumanios 19 3":["D"],
    "Dumanios 20 3":["D AMB"],
    "Dumanios 21 3":["IIT D"],
    "Dumanios 22 3":["D AMB"],
    "Dumanios 23 3":["D"],
    "Dumanios 24 3":["N INIS R"],
    "Dumanios 25 3":["D"],
    "Dumanios 26 3":["D AMB (N AMB)"],
    "Dumanios 27 3":["N INIS R"],
    "Dumanios 28 3":["D AMB"],
    "Dumanios 29 3":["D"],
    "Riuros 1 3":["D ANAGANT"],
    "Riuros 2 3":["PRINI LOUD"],
    "Riuros 3 3":["N"],
    "Riuros 4 3":["(MD) BRIGIOMU RIVRI"],
    "Riuros 5 3":["N INIS R"],
    "Riuros 6 3":["MD"],
    "Riuros 7 3":["MD"],
    "Riuros 8 3":["PRINI LOUD"],
    "Riuros 9 3":["ITI MD"],
    "Riuros 10 3":["IIT MD"],
    "Riuros 11 3":["N INIS R"],
    "Riuros 12 3":["MD"],
    "Riuros 13 3":["DEC/VOR LUG RIV"],
    "Riuros 14 3":["NSDS", "IVOS"],
    "Riuros 15 3":["N", "IVOS"],
    "Riuros 16 3":["MD", "IVOS"],
    "Riuros 17 3":["MD", "IVOS"],
    "Riuros 18 3":["D AMB", "IVOS"],
    "Riuros 19 3":["MD", "IVOS"],
    "Riuros 20 3":["TII D AMB", "IVOS"],
    "Riuros 21 3":["ITT MD"],
    "Riuros 22 3":["IIT D AMB"],
    "Riuros 23 3":["D PETIUX ANAG"],
    "Riuros 24 3":["N"],
    "Riuros 25 3":["IIT MD PETIUX RIVRI"],
    "Riuros 26 3":["TII D AMB", "IVOS"],
    "Riuros 27 3":["ITI MD", "IVOS"],
    "Riuros 28 3":["IIT D AMB", "IVOS"],
    "Riuros 29 3":["MD", "IVOS"],
    "Riuros 30 3":["D AMB", "IVOS"],
    "Anagantios 1 3":["MD RIVRI IX", "IVOS"],
    "Anagantios 2 3":["D", "IVOS"],
    "Anagantios 3 3":["D", "IVOS"],
    "Anagantios 4 3":["N OGIOUMU RIVRI"],
    "Anagantios 5 3":["N INIS R"],
    "Anagantios 6 3":["PRINI LAG"],
    "Anagantios 7 3":["NSDS"],
    "Anagantios 8 3":["D"],
    "Anagantios 9 3":["D"],
    "Anagantios 10 3":["D"],
    "Anagantios 11 3":["D AMB"],
    "Anagantios 12 3":["D"],
    "Anagantios 13 3":["D"],
    "Anagantios 14 3":["D"],
    "Anagantios 15 3":["D"],
    "Anagantios 16 3":["N"],
    "Anagantios 17 3":["D"],
    "Anagantios 18 3":["D AMB"],
    "Anagantios 19 3":["D"],
    "Anagantios 20 3":["D AMB"],
    "Anagantios 21 3":["N INIS R"],
    "Anagantios 22 3":["N INIS R"],
    "Anagantios 23 3":["D"],
    "Anagantios 24 3":["N INIS R"],
    "Anagantios 25 3":["D"],
    "Anagantios 26 3":["D AMB"],
    "Anagantios 27 3":["D"],
    "Anagantios 28 3":["D AMB"],
    "Anagantios 29 3":["D"],
    "Ogronios 1 3":["MD"],
    "Ogronios 2 3":["MD"],
    "Ogronios 3 3":["PRINI LOUD"],
    "Ogronios 4 3":["ITI MD"],
    "Ogronios 5 3":["N INIS R"],
    "Ogronios 6 3":["MD"],
    "Ogronios 7 3":["MD"],
    "Ogronios 8 3":["MD"],
    "Ogronios 9 3":["TII MD"],
    "Ogronios 10 3":["ITI MD"],
    "Ogronios 11 3":["IIT D AMB"],
    "Ogronios 12 3":["MD"],
    "Ogronios 13 3":["MD"],
    "Ogronios 14 3":["MD"],
    "Ogronios 15 3":["N"],
    "Ogronios 16 3":["TII MD CVTI"],
    "Ogronios 17 3":["N CVTI"],
    "Ogronios 18 3":["IIT D CVTI AMB"],
    "Ogronios 19 3":["MD"],
    "Ogronios 20 3":["D AMB"],
    "Ogronios 21 3":["TIT MD"],
    "Ogronios 22 3":["ITI D AMB"],
    "Ogronios 23 3":["ITI MD QVTI"],
    "Ogronios 24 3":["D AMB"],
    "Ogronios 25 3":["MD"],
    "Ogronios 26 3":["D AMB"],
    "Ogronios 27 3":["N INIS R"],
    "Ogronios 28 3":["ITI D AMB"],
    "Ogronios 29 3":["IIT MD"],
    "Ogronios 30 3":["D AMB"],
    "Cutios 1 3":["MD"],
    "Cutios 2 3":["MD"],
    "Cutios 3 3":["MD"],
    "Cutios 4 3":["PRINI LOUD"],
    "Cutios 5 3":["N INIS R"],
    "Cutios 6 3":["N"],
    "Cutios 7 3":["MD"],
    "Cutios 8 3":["MD"],
    "Cutios 9 3":["N INIS R"],
    "Cutios 10 3":["TII MD"],
    "Cutios 11 3":["ITI D AMB"],
    "Cutios 12 3":["IIT MD"],
    "Cutios 13 3":["MD"],
    "Cutios 14 3":["MD"],
    "Cutios 15 3":["MD"],
    "Cutios 16 3":["MD OGRON"],
    "Cutios 17 3":["MD OGRON"],
    "Cutios 18 3":["N OGRON"],
    "Cutios 19 3":["N INIS R"],
    "Cutios 20 3":["D AMB"],
    "Cutios 21 3":["N INIS R"],
    "Cutios 22 3":["TII D AMB"],
    "Cutios 23 3":["IIT MD OGRONI"],
    "Cutios 24 3":["IIT D AMB"],
    "Cutios 25 3":["MD"],
    "Cutios 26 3":["D AMB"],
    "Cutios 27 3":["MD"],
    "Cutios 28 3":["TII D AMB", "IVOS"],
    "Cutios 29 3":["ITI MD", "IVOS"],
    "Cutios 30 3":["IIT D AMB", "IVOS"],
    "Rantaranos 1 3":["D SAMON DUMAN", "IVOS"],
    "Rantaranos 2 3":["D DUMANI", "IVOS"],
    "Rantaranos 3 3":["(ITI) MD RIVRI", "IVOS"],
    "Rantaranos 4 3":["MD OCIOMV RIVRI AN\n--]T ANAG"],
    "Rantaranos 5 3":["N OGRON\nINNIS R"],
    "Rantaranos 6 3":["(IIT) MD CUTI"],
    "Rantaranos 7 3":["GIAMON PRINI LAG\n[---\n[---"],
    "Rantaranos 8 3":["D GIAM SIMVIS"],
    "Rantaranos 9 3":["N GIAMO EQVI\nINNIS R"],
    "Rantaranos 10 3":["N ELEMB INIS R"],
    "Rantaranos 11 3":["D EDRINI AMB"],
    "Rantaranos 12 3":["IIT D CANTLI"],
    "Rantaranos 13 3":["TII MD SAMONI"],
    "Rantaranos 14 3":["D DUMANNI"],
    "Rantaranos 15 3":["DS MD NS RIVR"],
    "Rantaranos 16 3":["D ANAGAN"],
    "Rantaranos 17 3":["ITI MD QVTI OGRON"],
    "Rantaranos 18 3":["D OGRONI QVT (AMB)"],
    "Rantaranos 19 3":["D GIAMONI"],
    "Rantaranos 20 3":["D SIMIS AMB"],
    "Rantaranos 21 3":["IIT D SIMIS EQUI"],
    "Rantaranos 22 3":["N GIAMONI\nELEMBI"],
    "Rantaranos 23 3":["N GIAMONI\nAEDRINNI"],
    "Rantaranos 24 3":["D GIAMO CANT\nAMB RIXR"],
    "Rantaranos 25 3":["TII MD SAMON"],
    "Rantaranos 26 3":["D DUMAN AMB"],
    "Rantaranos 27 3":["ITI MD RIVRI"],
    "Rantaranos 28 3":["D ANAG AMB"],
    "Rantaranos 29 3":["IIT D M OGRONV"],
    "Rantaranos 30 3":["IIT D AMB QVT"],
    "Giamonios 1 3":["MD SIMUISONNA"],
    "Giamonios 2 3":["D"],
    "Giamonios 3 3":["D"],
    "Giamonios 4 3":["D"],
    "Giamonios 5 3":["D AMB"],
    "Giamonios 6 3":["D"],
    "Giamonios 7 3":["IIT MD SIMIU TIOCOBREXTIO"],
    "Giamonios 8 3":["MD SIMIUSONNA"],
    "Giamonios 9 3":["MD SIMIU SINDIU", "IVOS"],
    "Giamonios 10 3":["D"],
    "Giamonios 11 3":["D AMB"],
    "Giamonios 12 3":["D"],
    "Giamonios 13 3":["D"],
    "Giamonios 14 3":["D"],
    "Giamonios 15 3":["D"],
    "Giamonios 16 3":["D"],
    "Giamonios 17 3":["NSDS"],
    "Giamonios 18 3":["D AMB"],
    "Giamonios 19 3":["D"],
    "Giamonios 20 3":["D AMB"],
    "Giamonios 21 3":["IIT D"],
    "Giamonios 22 3":["D SIMIUI AMB"],
    "Giamonios 23 3":["TII MD SIMIUISONNA"],
    "Giamonios 24 3":["ITI D SIMIUIS AMB"],
    "Giamonios 25 3":["D"],
    "Giamonios 26 3":["N INIS R"],
    "Giamonios 27 3":["D"],
    "Giamonios 28 3":["D AMB"],
    "Giamonios 29 3":["D"],
    "Simiuisonna 1 3":["GIAM PRINI LAG"],
    "Simiuisonna 2 3":["MD"],
    "Simiuisonna 3 3":["D EQVI"],
    "Simiuisonna 4 3":["MD"],
    "Simiuisonna 5 3":["N INIS R"],
    "Simiuisonna 6 3":["D EQVI"],
    "Simiuisonna 7 3":["D EQVI"],
    "Simiuisonna 8 3":["PRINI LAG EQVI"],
    "Simiuisonna 9 3":["D EQVI"],
    "Simiuisonna 10 3":["MD"],
    "Simiuisonna 11 3":["TII D AMB"],
    "Simiuisonna 12 3":["ITI MD"],
    "Simiuisonna 13 3":["D EQVI"],
    "Simiuisonna 14 3":["NSDS EQVI"],
    "Simiuisonna 15 3":["DSND EQVI"],
    "Simiuisonna 16 3":["D EQVI"],
    "Simiuisonna 17 3":["D EQVI"],
    "Simiuisonna 18 3":["D EQVI AMB"],
    "Simiuisonna 19 3":["IIT MD"],
    "Simiuisonna 20 3":["D AMB"],
    "Simiuisonna 21 3":["ITT D EQVI"],
    "Simiuisonna 22 3":["D EQVI AMB"],
    "Simiuisonna 23 3":["D EQVI"],
    "Simiuisonna 24 3":["D AMB EQVI"],
    "Simiuisonna 25 3":["IIT MD"],
    "Simiuisonna 26 3":["D AMB", "IVOS"],
    "Simiuisonna 27 3":["MD", "IVOS"],
    "Simiuisonna 28 3":["D AMB", "IVOS"],
    "Simiuisonna 29 3":["NSDS", "IVOS"],
    "Simiuisonna 30 3":["DSNS", "IVOS"],
    "Equos 1 3":["D", "IVOS"],
    "Equos 2 3":["PRINI LAG", "IVOS"],
    "Equos 3 3":["MD SIMIVIS", "IVOS"],
    "Equos 4 3":["D", "IVOS"],
    "Equos 5 3":["D AMB"],
    "Equos 6 3":["ITI MD SIMIVISO"],
    "Equos 7 3":["D ELEMB"],
    "Equos 8 3":["D ELEMB"],
    "Equos 9 3":["D ELEMB"],
    "Equos 10 3":["D"],
    "Equos 11 3":["D AMB"],
    "Equos 12 3":["D"],
    "Equos 13 3":["IIT MD SIMI"],
    "Equos 14 3":["MD SIMI"],
    "Equos 15 3":["MD SIMI"],
    "Equos 16 3":["MD SIMIVIS"],
    "Equos 17 3":["TII MD SIMIVIS"],
    "Equos 18 3":["ITI D AMB SIMIVIS"],
    "Equos 19 3":["D"],
    "Equos 20 3":["TII D AMB"],
    "Equos 21 3":["IIT MD SIMIVIS"],
    "Equos 22 3":["D ELEMB AMB"],
    "Equos 23 3":["D ELEMB"],
    "Equos 24 3":["D AMB ELEMB"],
    "Equos 25 3":["D"],
    "Equos 26 3":["D AMB"],
    "Equos 27 3":["D"],
    "Equos 28 3":["D AMB"],
    "Equos 29 3":["D"],
    "Elembi 1 3":["D", "IVOS"],
    "Elembi 2 3":["D", "IVOS"],
    "Elembi 3 3":["PRINI LAG", "IVOS"],
    "Elembi 4 3":["D"],
    "Elembi 5 3":["D AMB"],
    "Elembi 6 3":["D"],
    "Elembi 7 3":["ITI MD EDRINNI TIOGBR?"],
    "Elembi 8 3":["IIT MD EDRI TIOCOBREXTIO"],
    "Elembi 9 3":["MD EDRINNI"],
    "Elembi 10 3":["N INIS R"],
    "Elembi 11 3":["D"],
    "Elembi 12 3":["D"],
    "Elembi 13 3":["D"],
    "Elembi 14 3":["D"],
    "Elembi 15 3":["D"],
    "Elembi 16 3":["MD EDRIN"],
    "Elembi 17 3":["MD EDRIN"],
    "Elembi 18 3":["TII D EDRIN AMB"],
    "Elembi 19 3":["D"],
    "Elembi 20 3":["D AMB"],
    "Elembi 21 3":["IIT D"],
    "Elembi 22 3":["D EDRIN AMB"],
    "Elembi 23 3":["MD EDRINI"],
    "Elembi 24 3":["TII D AMB EDRINI"],
    "Elembi 25 3":["D SINDIU IVOS"],
    "Elembi 26 3":["D AMB"],
    "Elembi 27 3":["D"],
    "Elembi 28 3":["D AMB"],
    "Elembi 29 3":["D"],
    "Aedrinni 1 3":["D CANTLI"],
    "Aedrinni 2 3":["MD"],
    "Aedrinni 3 3":["MD"],
    "Aedrinni 4 3":["MD"],
    "Aedrinni 5 3":["D AMB"],
    "Aedrinni 6 3":["PRINI LOUD"],
    "Aedrinni 7 3":["D CANTI"],
    "Aedrinni 8 3":["D CANTI"],
    "Aedrinni 9 3":["D CANTI"],
    "Aedrinni 10 3":["MD"],
    "Aedrinni 11 3":["D AMB"],
    "Aedrinni 12 3":["TII MD"],
    "Aedrinni 13 3":["ITI MD"],
    "Aedrinni 14 3":["IIT MD"],
    "Aedrinni 15 3":["MD"],
    "Aedrinni 16 3":["D ELEMB"],
    "Aedrinni 17 3":["D ELEMB"],
    "Aedrinni 18 3":["D AMB ELEMB"],
    "Aedrinni 19 3":["ITI MD"],
    "Aedrinni 20 3":["IIT D AMB"],
    "Aedrinni 21 3":["IIT MD"],
    "Aedrinni 22 3":["D CANTLAMB"],
    "Aedrinni 23 3":["D CANTL"],
    "Aedrinni 24 3":["D CANTLAMB"],
    "Aedrinni 25 3":["ITI MD"],
    "Aedrinni 26 3":["IIT D AMB"],
    "Aedrinni 27 3":["MD"],
    "Aedrinni 28 3":["D AMB", "IVOS"],
    "Aedrinni 29 3":["MD", "IVOS"],
    "Aedrinni 30 3":["N", "IVOS"],
    "Cantlos 1 3":["MD AEDRIN", "IVOS"],
    "Cantlos 2 3":["D", "IVOS"],
    "Cantlos 3 3":["D", "IVOS"],
    "Cantlos 4 3":["PRINI LAG"],
    "Cantlos 5 3":["D AMB"],
    "Cantlos 6 3":["D"],
    "Cantlos 7 3":["SAMON PRINI LOUD"],
    "Cantlos 8 3":["D DUMANNI (SAMONI)"],
    "Cantlos 9 3":["MD SAMONI"],
    "Cantlos 10 3":["D"],
    "Cantlos 11 3":["D AMB"],
    "Cantlos 12 3":["D"],
    "Cantlos 13 3":["D"],
    "Cantlos 14 3":["D"],
    "Cantlos 15 3":["D TIOCOBREXTIO"],
    "Cantlos 16 3":["D"],
    "Cantlos 17 3":["D"],
    "Cantlos 18 3":["D AMB"],
    "Cantlos 19 3":["N INIS R"],
    "Cantlos 20 3":["D AMB"],
    "Cantlos 21 3":["IIT D"],
    "Cantlos 22 3":["D AMB SAMONI"],
    "Cantlos 23 3":["N SAMONI INIS R"],
    "Cantlos 24 3":["N SAMONI INIS R"],
    "Cantlos 25 3":["D"],
    "Cantlos 26 3":["D AMB", "IVOS"],
    "Cantlos 27 3":["D", "IVOS"],
    "Cantlos 28 3":["D AMB", "IVOS"],
    "Cantlos 29 3":["D", "IVOS"],
    "Samonios 1 4":["D DUMANNI", "IVOS"],
    "Samonios 2 4":["MD", "IVOS"],
    "Samonios 3 4":["D EXINGI DUM", "IVOS"],
    "Samonios 4 4":["MD", "IVOS"],
    "Samonios 5 4":["D AMB"],
    "Samonios 6 4":["MD"],
    "Samonios 7 4":["N DUMAN INIS R"],
    "Samonios 8 4":["MD SAMONI"],
    "Samonios 9 4":["D DUMANI"],
    "Samonios 10 4":["MD"],
    "Samonios 11 4":["D AMB"],
    "Samonios 12 4":["MD"],
    "Samonios 13 4":["TII MD"],
    "Samonios 14 4":["ITI MD"],
    "Samonios 15 4":["IIT MD"],
    "Samonios 16 4":["D DUMANI"],
    "Samonios 17 4":["(M)D PRINI (TRINUX) SAM SINDIV", "(IVOS)"],
    "Samonios 18 4":["D AMB"],
    "Samonios 19 4":["TII MD"],
    "Samonios 20 4":["ITI D AMB"],
    "Samonios 21 4":["IIT MD"],
    "Samonios 22 4":["D DUM AMB"],
    "Samonios 23 4":["D DUMANI"],
    "Samonios 24 4":["N DUM INIS R"],
    "Samonios 25 4":["TII MD"],
    "Samonios 26 4":["ITI D AMB"],
    "Samonios 27 4":["IIT MD"],
    "Samonios 28 4":["D AMB"],
    "Samonios 29 4":["MD"],
    "Samonios 30 4":["D AMB"],
    "Dumanios 1 4":["SAMON PRINI LOUD"],
    "Dumanios 2 4":["D"],
    "Dumanios 3 4":["D"],
    "Dumanios 4 4":["D"],
    "Dumanios 5 4":["PRINI LAG"],
    "Dumanios 6 4":["D"],
    "Dumanios 7 4":["MD RIVRI"],
    "Dumanios 8 4":["MD RIVRI"],
    "Dumanios 9 4":["MD RIVRI"],
    "Dumanios 10 4":["D"],
    "Dumanios 11 4":["N INIS R"],
    "Dumanios 12 4":["D"],
    "Dumanios 13 4":["D", "IVOS"],
    "Dumanios 14 4":["D", "IVOS"],
    "Dumanios 15 4":["D", "IVOS"],
    "Dumanios 16 4":["MD SAMONI", "IVOS"],
    "Dumanios 17 4":["MD SAMONI", "IVOS"],
    "Dumanios 18 4":["D AMB", "IVOS"],
    "Dumanios 19 4":["D", "IVOS"],
    "Dumanios 20 4":["D AMB", "IVOS"],
    "Dumanios 21 4":["IIT D"],
    "Dumanios 22 4":["IIT D RIVRI AMB"],
    "Dumanios 23 4":["D PETIUX RIV ANAG"],
    "Dumanios 24 4":["D AMB RIVRI"],
    "Dumanios 25 4":["D"],
    "Dumanios 26 4":["D AMB", "[IVOS]"],
    "Dumanios 27 4":["N INIS R", "[IVOS]"],
    "Dumanios 28 4":["D AMB", "IVOS"],
    "Dumanios 29 4":["D", "IVOS"],
    "Riuros 1 4":["D ANAGANT EXO", "IVOS"],
    "Riuros 2 4":["PRINI LOUD", "IVOS"],
    "Riuros 3 4":["MD", "IVOS"],
    "Riuros 4 4":["(MD) BRIGIOMU RIVRI"],
    "Riuros 5 4":["N INIS R"],
    "Riuros 6 4":["MD"],
    "Riuros 7 4":["D ANAGANTIOS"],
    "Riuros 8 4":["D ANAGANT"],
    "Riuros 9 4":["D ANAGANT"],
    "Riuros 10 4":["MD"],
    "Riuros 11 4":["N INIS R"],
    "Riuros 12 4":["MD"],
    "Riuros 13 4":["DEC/VOR LUG RIVRI"],
    "Riuros 14 4":["NSDS MAT"],
    "Riuros 15 4":["DS MAT NS"],
    "Riuros 16 4":["MD"],
    "Riuros 17 4":["MD"],
    "Riuros 18 4":["D AMB"],
    "Riuros 19 4":["MD"],
    "Riuros 20 4":["TII D AMB"],
    "Riuros 21 4":["ITT MD"],
    "Riuros 22 4":["N ANAG INIS R"],
    "Riuros 23 4":["D ANAG"],
    "Riuros 24 4":["N ANAG INIS R"],
    "Riuros 25 4":["MD PETIUX RIVRI"],
    "Riuros 26 4":["TII D AMB"],
    "Riuros 27 4":["ITI MD"],
    "Riuros 28 4":["IIT D AMB"],
    "Riuros 29 4":["MD"],
    "Riuros 30 4":["D"],
    "Anagantios 1 4":["MD RIVRI"],
    "Anagantios 2 4":["D"],
    "Anagantios 3 4":["D"],
    "Anagantios 4 4":["MD OGIOUMU RIVRI"],
    "Anagantios 5 4":["N INIS R"],
    "Anagantios 6 4":["PRINI LAG (ANAG)"],
    "Anagantios 7 4":["MD OGRONI"],
    "Anagantios 8 4":["MD OGRONI"],
    "Anagantios 9 4":["MD OGRONI"],
    "Anagantios 10 4":["D"],
    "Anagantios 11 4":["D AMB"],
    "Anagantios 12 4":["D"],
    "Anagantios 13 4":["D"],
    "Anagantios 14 4":["D"],
    "Anagantios 15 4":["D"],
    "Anagantios 16 4":["D"],
    "Anagantios 17 4":["D"],
    "Anagantios 18 4":["D AMB"],
    "Anagantios 19 4":["D"],
    "Anagantios 20 4":["D AMB"],
    "Anagantios 21 4":["N INIS R"],
    "Anagantios 22 4":["ITI D AMB OGRON"],
    "Anagantios 23 4":["ITI MD CVTI OGRON"],
    "Anagantios 24 4":["D OGRON AMB"],
    "Anagantios 25 4":["NSDS"],
    "Anagantios 26 4":["D AMB"],
    "Anagantios 27 4":["D"],
    "Anagantios 28 4":["D AMB"],
    "Anagantios 29 4":["D"],
    "Ogronios 1 4":["MD"],
    "Ogronios 2 4":["MD"],
    "Ogronios 3 4":["PRINI LOUD"],
    "Ogronios 4 4":["MD"],
    "Ogronios 5 4":["N INIS R"],
    "Ogronios 6 4":["MD"],
    "Ogronios 7 4":["MD CVTIO"],
    "Ogronios 8 4":["MD CVTIO"],
    "Ogronios 9 4":["N CVTIO INIS R"],
    "Ogronios 10 4":["MD"],
    "Ogronios 11 4":["D AMB"],
    "Ogronios 12 4":["MD"],
    "Ogronios 13 4":["MD"],
    "Ogronios 14 4":["MD"],
    "Ogronios 15 4":["N"],
    "Ogronios 16 4":["TII MD CVTI"],
    "Ogronios 17 4":["ITI MD CVTI"],
    "Ogronios 18 4":["TII D CVTI AMB"],
    "Ogronios 19 4":["MD"],
    "Ogronios 20 4":["D AMB"],
    "Ogronios 21 4":["TIT MD"],
    "Ogronios 22 4":["TII D AMB QVTI"],
    "Ogronios 23 4":["ITI MD OGRON QVTI"],
    "Ogronios 24 4":["IIT D AMB QVTI"],
    "Ogronios 25 4":["MD"],
    "Ogronios 26 4":["D AMB"],
    "Ogronios 27 4":["N INIS R"],
    "Ogronios 28 4":["ITI D AMB", "IVOS"],
    "Ogronios 29 4":["IIT MD", "IVOS"],
    "Ogronios 30 4":["D AMB", "IVOS"],
    "Cutios 1 4":["MD"],
    "Cutios 2 4":["MD"],
    "Cutios 3 4":["MD"],
    "Cutios 4 4":["PRINI LOUD"],
    "Cutios 5 4":["N INIS R"],
    "Cutios 6 4":["MD"],
    "Cutios 7 4":["MD CVTIO"],
    "Cutios 8 4":["MD CVTIO"],
    "Cutios 9 4":["N CVTIO INIS R"],
    "Cutios 10 4":["MD"],
    "Cutios 11 4":["D AMB"],
    "Cutios 12 4":["MD"],
    "Cutios 13 4":["MD"],
    "Cutios 14 4":["MD"],
    "Cutios 15 4":["MD"],
    "Cutios 16 4":["MD OGRON"],
    "Cutios 17 4":["MD OGRON"],
    "Cutios 18 4":["D OGRON AMB"],
    "Cutios 19 4":["N INIS R"],
    "Cutios 20 4":["D AMB"],
    "Cutios 21 4":["N INIS R"],
    "Cutios 22 4":["TII D AMB QVTI"],
    "Cutios 23 4":["ITI MD OGRON QVTIO"],
    "Cutios 24 4":["TII D AMB QVTI"],
    "Cutios 25 4":["MD"],
    "Cutios 26 4":["D AMB"],
    "Cutios 27 4":["MD"],
    "Cutios 28 4":["TII D AMB", "IVOS"],
    "Cutios 29 4":["ITI MD", "IVOS"],
    "Cutios 30 4":["IIT D AMB", "IVOS"],
    "Giamonios 1 4":["N SIMIUISONNA EXO", "IVOS"],
    "Giamonios 2 4":["ITI D", "IVOS"],
    "Giamonios 3 4":["IIT D", "IVOS"],
    "Giamonios 4 4":["D"],
    "Giamonios 5 4":["D AMB"],
    "Giamonios 6 4":["D"],
    "Giamonios 7 4":["PRINI LAG"],
    "Giamonios 8 4":["ITI D"],
    "Giamonios 9 4":["N INIS R"],
    "Giamonios 10 4":["D"],
    "Giamonios 11 4":["D AMB"],
    "Giamonios 12 4":["D"],
    "Giamonios 13 4":["TII D"],
    "Giamonios 14 4":["ITI D"],
    "Giamonios 15 4":["IIT D"],
    "Giamonios 16 4":["D"],
    "Giamonios 17 4":["NSDS"],
    "Giamonios 18 4":["D AMB"],
    "Giamonios 19 4":["TII D"],
    "Giamonios 20 4":["ITI D AMB"],
    "Giamonios 21 4":["IIT D"],
    "Giamonios 22 4":["N INIS R"],
    "Giamonios 23 4":["N INIS R"],
    "Giamonios 24 4":["D AMB"],
    "Giamonios 25 4":["TII D"],
    "Giamonios 26 4":["N INIS R"],
    "Giamonios 27 4":["IIT D"],
    "Giamonios 28 4":["D AMB"],
    "Giamonios 29 4":["D"],
    "Simiuisonna 1 4":["GIAM PRINI LAG"],
    "Simiuisonna 2 4":["N"],
    "Simiuisonna 3 4":["ITI D EQVI"],
    "Simiuisonna 4 4":["MD"],
    "Simiuisonna 5 4":["N INIS R"],
    "Simiuisonna 6 4":["D EQVI"],
    "Simiuisonna 7 4":["MD TIOCOBREXTIO"],
    "Simiuisonna 8 4":["MD"],
    "Simiuisonna 9 4":["MD SINIDIU", "IVOS"],
    "Simiuisonna 10 4":["MD"],
    "Simiuisonna 11 4":["D AMB"],
    "Simiuisonna 12 4":["MD"],
    "Simiuisonna 13 4":["D EQVI"],
    "Simiuisonna 14 4":["NSDS EQVI"],
    "Simiuisonna 15 4":["DSNS EQVI"],
    "Simiuisonna 16 4":["D EQVI"],
    "Simiuisonna 17 4":["D EQVI"],
    "Simiuisonna 18 4":["D AMB EQVI"],
    "Simiuisonna 19 4":["IIT MD"],
    "Simiuisonna 20 4":["D AMB"],
    "Simiuisonna 21 4":["ITT D EQVI"],
    "Simiuisonna 22 4":["D AMB"],
    "Simiuisonna 23 4":["TII MD"],
    "Simiuisonna 24 4":["ITI D AMB"],
    "Simiuisonna 25 4":["IIT MD"],
    "Simiuisonna 26 4":["D AMB"],
    "Simiuisonna 27 4":["MD"],
    "Simiuisonna 28 4":["D AMB"],
    "Simiuisonna 29 4":["NSDS"],
    "Simiuisonna 30 4":["DSNS"],
    "Equos 1 4":["D"],
    "Equos 2 4":["PRINI LAG"],
    "Equos 3 4":["N SIMIVIS"],
    "Equos 4 4":["IIT D"],
    "Equos 5 4":["D AMB"],
    "Equos 6 4":["MD SIMIVISO"],
    "Equos 7 4":["D"],
    "Equos 8 4":["PRINI LAG"],
    "Equos 9 4":["ITI D"],
    "Equos 10 4":["IIT D"],
    "Equos 11 4":["D AMB"],
    "Equos 12 4":["D"],
    "Equos 13 4":["MD SIMI"],
    "Equos 14 4":["MD SIMI"],
    "Equos 15 4":["MD SIMI"],
    "Equos 16 4":["MD SIMIVIS"],
    "Equos 17 4":["TII MD SIMIVIS"],
    "Equos 18 4":["ITI D AMB SIMIVIS"],
    "Equos 19 4":["D"],
    "Equos 20 4":["TII D AMB"],
    "Equos 21 4":["IIT MD SIMIVIS"],
    "Equos 22 4":["IIT D AMB"],
    "Equos 23 4":["D"],
    "Equos 24 4":["D AMB"],
    "Equos 25 4":["D"],
    "Equos 26 4":["TII D AMB", "IVOS"],
    "Equos 27 4":["ITI D", "IVOS"],
    "Equos 28 4":["IIT D AMB", "IVOS"],
    "Equos 29 4":["D", "IVOS"],
    "Elembi 1 4":["D", "IVOS"],
    "Elembi 2 4":["D", "IVOS"],
    "Elembi 3 4":["PRINI LAG", "IVOS"],
    "Elembi 4 4":["N", "IVOS"],
    "Elembi 5 4":["IIT D AMB"],
    "Elembi 6 4":["D"],
    "Elembi 7 4":["D"],
    "Elembi 8 4":["D"],
    "Elembi 9 4":["PRINI LAG"],
    "Elembi 10 4":["N INIS R"],
    "Elembi 11 4":["IIT D AMB"],
    "Elembi 12 4":["D"],
    "Elembi 13 4":["D"],
    "Elembi 14 4":["D"],
    "Elembi 15 4":["N"],
    "Elembi 16 4":["MD EDRIN"],
    "Elembi 17 4":["MD EDRIN"],
    "Elembi 18 4":["TII D EDRIN AMB"],
    "Elembi 19 4":["D"],
    "Elembi 20 4":["D AMB"],
    "Elembi 21 4":["TIT D"],
    "Elembi 22 4":["ITI D AMB"],
    "Elembi 23 4":["IIT D"],
    "Elembi 24 4":["D AMB"],
    "Elembi 25 4":["D"],
    "Elembi 26 4":["D AMB"],
    "Elembi 27 4":["TII D"],
    "Elembi 28 4":["ITI D AMB"],
    "Elembi 29 4":["IIT D"],
    "Aedrinni 1 4":["D CANTLI", "IVOS"],
    "Aedrinni 2 4":["MD", "IVOS"],
    "Aedrinni 3 4":["MD", "IVOS"],
    "Aedrinni 4 4":["MD"],
    "Aedrinni 5 4":["N"],
    "Aedrinni 6 4":["PRINI LOUD"],
    "Aedrinni 7 4":["MD [TIOGBR?]"],
    "Aedrinni 8 4":["MD TIOCOBREXTIO"],
    "Aedrinni 9 4":["MD"],
    "Aedrinni 10 4":["MD"],
    "Aedrinni 11 4":["D AMB"],
    "Aedrinni 12 4":["MD"],
    "Aedrinni 13 4":["MD"],
    "Aedrinni 14 4":["MD"],
    "Aedrinni 15 4":["MD"],
    "Aedrinni 16 4":["D ELEMB"],
    "Aedrinni 17 4":["D ELEMB"],
    "Aedrinni 18 4":["D ELEMB AMB"],
    "Aedrinni 19 4":["ITI MD"],
    "Aedrinni 20 4":["IIT D AMB"],
    "Aedrinni 21 4":["IIT MD"],
    "Aedrinni 22 4":["D AMB"],
    "Aedrinni 23 4":["MD"],
    "Aedrinni 24 4":["TII D AMB"],
    "Aedrinni 25 4":["ITI D SINDIV", "IVOS"],
    "Aedrinni 26 4":["IIT D AMB"],
    "Aedrinni 27 4":["MD"],
    "Aedrinni 28 4":["D AMB"],
    "Aedrinni 29 4":["MD"],
    "Aedrinni 30 4":["N"],
    "Cantlos 1 4":["MD AEDRIN"],
    "Cantlos 2 4":["D"],
    "Cantlos 3 4":["D"],
    "Cantlos 4 4":["PRINI LAG"],
    "Cantlos 5 4":["ITI D AMB"],
    "Cantlos 6 4":["N"],
    "Cantlos 7 4":["D"],
    "Cantlos 8 4":["D"],
    "Cantlos 9 4":["D"],
    "Cantlos 10 4":["TII D"],
    "Cantlos 11 4":["ITI D AMB"],
    "Cantlos 12 4":["IIT D"],
    "Cantlos 13 4":["D"],
    "Cantlos 14 4":["D"],
    "Cantlos 15 4":["D TIOCOBREXTIO"],
    "Cantlos 16 4":["TII D"],
    "Cantlos 17 4":["ITI D"],
    "Cantlos 18 4":["IIT D AMB"],
    "Cantlos 19 4":["N INIS R"],
    "Cantlos 20 4":["D AMB"],
    "Cantlos 21 4":["IIT D"],
    "Cantlos 22 4":["TII D AMB"],
    "Cantlos 23 4":["ITI D"],
    "Cantlos 24 4":["IIT D AMB"],
    "Cantlos 25 4":["D"],
    "Cantlos 26 4":["D AMB"],
    "Cantlos 27 4":["D"],
    "Cantlos 28 4":["TII D AMB", "IVOS"],
    "Cantlos 29 4":["ITI D", "IVOS"],
    "Samonios 1 5":["D DUMANNI", "IVOS"],
    "Samonios 2 5":["MD", "IVOS"],
    "Samonios 3 5":["TII D DUM ALE", "IVOS"],
    "Samonios 4 5":["MD"],
    "Samonios 5 5":["D AMB"],
    "Samonios 6 5":["MD"],
    "Samonios 7 5":["N PRINI LOUDIN"],
    "Samonios 8 5":["D DUMANI"],
    "Samonios 9 5":["MD"],
    "Samonios 10 5":["MD"],
    "Samonios 11 5":["D AMB"],
    "Samonios 12 5":["MD"],
    "Samonios 13 5":["MD"],
    "Samonios 14 5":["MD"],
    "Samonios 15 5":["MD"],
    "Samonios 16 5":["D DUMANNI"],
    "Samonios 17 5":["MD TRINO SAM"],
    "Samonios 18 5":["D AMB"],
    "Samonios 19 5":["TII MD"],
    "Samonios 20 5":["ITI D AMB"],
    "Samonios 21 5":["IIT MD"],
    "Samonios 22 5":["D AMB"],
    "Samonios 23 5":["N INIS R"],
    "Samonios 24 5":["N INIS R"],
    "Samonios 25 5":["TII MD"],
    "Samonios 26 5":["ITI D AMB", "IVOS"],
    "Samonios 27 5":["IIT MD", "IVOS"],
    "Samonios 28 5":["D AMB", "IVOS"],
    "Samonios 29 5":["MD", "IVOS"],
    "Samonios 30 5":["D AMB", "IVOS"],
    "Dumanios 1 5":["SAM PRINI LOUD EXO", "IVOS"],
    "Dumanios 2 5":["D", "IVOS"],
    "Dumanios 3 5":["D", "IVOS"],
    "Dumanios 4 5":["D", "IVOS"],
    "Dumanios 5 5":["PRINI LAGET"],
    "Dumanios 6 5":["ITI D"],
    "Dumanios 7 5":["N INIS R"],
    "Dumanios 8 5":["N SAMONI"],
    "Dumanios 9 5":["D"],
    "Dumanios 10 5":["D"],
    "Dumanios 11 5":["N INIS R"],
    "Dumanios 12 5":["ITI D"],
    "Dumanios 13 5":["IIT D"],
    "Dumanios 14 5":["D"],
    "Dumanios 15 5":["D"],
    "Dumanios 16 5":["MD SAMONI"],
    "Dumanios 17 5":["MD SAMONI"],
    "Dumanios 18 5":["ITI D AMB"],
    "Dumanios 19 5":["IIT D"],
    "Dumanios 20 5":["D AMB"],
    "Dumanios 21 5":["IIT M D"],
    "Dumanios 22 5":["D AMB"],
    "Dumanios 23 5":["TII D"],
    "Dumanios 24 5":["N INIS R"],
    "Dumanios 25 5":["IIT D"],
    "Dumanios 26 5":["D AMB"],
    "Dumanios 27 5":["N INIS R"],
    "Dumanios 28 5":["D AMB"],
    "Dumanios 29 5":["NSDS"],
    "Riuros 1 5":["D ANAGANT"],
    "Riuros 2 5":["PRINI LOUD"],
    "Riuros 3 5":["MD"],
    "Riuros 4 5":["(MD) BRIGIOMU RIVRI"],
    "Riuros 5 5":["N INIS R"],
    "Riuros 6 5":["MD"],
    "Riuros 7 5":["MD"],
    "Riuros 8 5":["PRINI LOUD"],
    "Riuros 9 5":["N"],
    "Riuros 10 5":["MD"],
    "Riuros 11 5":["N INIS R"],
    "Riuros 12 5":["MD"],
    "Riuros 13 5":["DEC/VOR LUG RIV"],
    "Riuros 14 5":["MD", "IVOS"],
    "Riuros 15 5":["MD", "IVOS"],
    "Riuros 16 5":["MD", "IVOS"],
    "Riuros 17 5":["MD", "IVOS"],
    "Riuros 18 5":["D AMB", "IVOS"],
    "Riuros 19 5":["MD", "IVOS"],
    "Riuros 20 5":["[TII] D AMB", "IVOS"],
    "Riuros 21 5":["[ITT] IIT MD"],
    "Riuros 22 5":["[IIT] D AMB"],
    "Riuros 23 5":["D PETIUX ANAG"],
    "Riuros 24 5":["D AMB"],
    "Riuros 25 5":["MD PETIUX RIVRI"],
    "Riuros 26 5":["TII D AMB", "IVOS"],
    "Riuros 27 5":["ITI MD", "IVOS"],
    "Riuros 28 5":["IIT D AMB", "IVOS"],
    "Riuros 29 5":["MD", "IVOS"],
    "Riuros 30 5":["D AMB", "IVOS"],
    "Anagantios 1 5":["MD RIVRI IX", "IVOS"],
    "Anagantios 2 5":["D", "IVOS"],
    "Anagantios 3 5":["D", "IVOS"],
    "Anagantios 4 5":["MD OGIOUMU RVRI"],
    "Anagantios 5 5":["N INIS R"],
    "Anagantios 6 5":["PRINI LAG"],
    "Anagantios 7 5":["ITI D"],
    "Anagantios 8 5":["IIT D"],
    "Anagantios 9 5":["D"],
    "Anagantios 10 5":["N"],
    "Anagantios 11 5":["D AMB"],
    "Anagantios 12 5":["TII D"],
    "Anagantios 13 5":["ITI D"],
    "Anagantios 14 5":["IIT D"],
    "Anagantios 15 5":["D"],
    "Anagantios 16 5":["D"],
    "Anagantios 17 5":["D"],
    "Anagantios 18 5":["TII D AMB"],
    "Anagantios 19 5":["ITI D"],
    "Anagantios 20 5":["IIT D AMB"],
    "Anagantios 21 5":["N INIS R"],
    "Anagantios 22 5":["N INIS R"],
    "Anagantios 23 5":["D"],
    "Anagantios 24 5":["N INIS R"],
    "Anagantios 25 5":["ITI D"],
    "Anagantios 26 5":["IIT D AMB"],
    "Anagantios 27 5":["D"],
    "Anagantios 28 5":["D AMB"],
    "Anagantios 29 5":["D"],
    "Ogronios 1 5":["MD"],
    "Ogronios 2 5":["MD"],
    "Ogronios 3 5":["PRINI LOUD"],
    "Ogronios 4 5":["MD"],
    "Ogronios 5 5":["N INIS R"],
    "Ogronios 6 5":["MD"],
    "Ogronios 7 5":["MD"],
    "Ogronios 8 5":["MD"],
    "Ogronios 9 5":["MD"],
    "Ogronios 10 5":["MD"],
    "Ogronios 11 5":["N"],
    "Ogronios 12 5":["MD"],
    "Ogronios 13 5":["MD"],
    "Ogronios 14 5":["MD"],
    "Ogronios 15 5":["MD"],
    "Ogronios 16 5":["MD CVTIO"],
    "Ogronios 17 5":["MD CVTIO"],
    "Ogronios 18 5":["D CVTIO AMB"],
    "Ogronios 19 5":["MD"],
    "Ogronios 20 5":["D AMB"],
    "Ogronios 21 5":["IIT MD"],
    "Ogronios 22 5":["D AMB"],
    "Ogronios 23 5":["MD QVTIO"],
    "Ogronios 24 5":["D AMB"],
    "Ogronios 25 5":["MD"],
    "Ogronios 26 5":["D AMB"],
    "Ogronios 27 5":["N INIS R"],
    "Ogronios 28 5":["ITI D AMB"],
    "Ogronios 29 5":["IIT MD"],
    "Ogronios 30 5":["D AMB"],
    "Cutios 1 5":["MD"],
    "Cutios 2 5":["MD"],
    "Cutios 3 5":["MD"],
    "Cutios 4 5":["PRINI LOUD"],
    "Cutios 5 5":["N INIS R"],
    "Cutios 6 5":["MD"],
    "Cutios 7 5":["MD"],
    "Cutios 8 5":["MD"],
    "Cutios 9 5":["N INIS R"],
    "Cutios 10 5":["MD"],
    "Cutios 11 5":["D AMB"],
    "Cutios 12 5":["N"],
    "Cutios 13 5":["MD"],
    "Cutios 14 5":["MD"],
    "Cutios 15 5":["MD"],
    "Cutios 16 5":["MD OGRON"],
    "Cutios 17 5":["MD OGRON"],
    "Cutios 18 5":["D OGRON AMB"],
    "Cutios 19 5":["N INIS R"],
    "Cutios 20 5":["D AMB"],
    "Cutios 21 5":["N INIS R"],
    "Cutios 22 5":["D AMB"],
    "Cutios 23 5":["MD OGRONI"],
    "Cutios 24 5":["D AMB"],
    "Cutios 25 5":["MD"],
    "Cutios 26 5":["D AMB"],
    "Cutios 27 5":["MD"],
    "Cutios 28 5":["D AMB", "IVOS"],
    "Cutios 29 5":["MD", "IVOS"],
    "Cutios 30 5":["D AMB", "IVOS"],
    "Giamonios 1 5":["N SIMIUISONNA EXO", "IVOS"],
    "Giamonios 2 5":["ITI D", "IVOS"],
    "Giamonios 3 5":["IIT D", "IVOS"],
    "Giamonios 4 5":["D"],
    "Giamonios 5 5":["D AMB"],
    "Giamonios 6 5":["D"],
    "Giamonios 7 5":["PRINI LAG"],
    "Giamonios 8 5":["ITI D"],
    "Giamonios 9 5":["N INIS R"],
    "Giamonios 10 5":["D"],
    "Giamonios 11 5":["D AMB"],
    "Giamonios 12 5":["D"],
    "Giamonios 13 5":["N"],
    "Giamonios 14 5":["ITI D"],
    "Giamonios 15 5":["IIT D"],
    "Giamonios 16 5":["D"],
    "Giamonios 17 5":["NSDS"],
    "Giamonios 18 5":["D AMB"],
    "Giamonios 19 5":["TII D"],
    "Giamonios 20 5":["ITI D AMB"],
    "Giamonios 21 5":["IIT D"],
    "Giamonios 22 5":["N INIS R"],
    "Giamonios 23 5":["N INIS R"],
    "Giamonios 24 5":["D AMB"],
    "Giamonios 25 5":["TII D"],
    "Giamonios 26 5":["N INIS R"],
    "Giamonios 27 5":["IIT D"],
    "Giamonios 28 5":["D AMB"],
    "Giamonios 29 5":["D"],
    "Simiuisonna 1 5":["GIAM PRINI LAG"],
    "Simiuisonna 2 5":["N"],
    "Simiuisonna 3 5":["ITI D EQVI"],
    "Simiuisonna 4 5":["MD"],
    "Simiuisonna 5 5":["N INIS R"],
    "Simiuisonna 6 5":["D EQVI"],
    "Simiuisonna 7 5":["MD TIOCOBREXTIO"],
    "Simiuisonna 8 5":["MD"],
    "Simiuisonna 9 5":["MD SINDIU", "IVOS"],
    "Simiuisonna 10 5":["MD"],
    "Simiuisonna 11 5":["D AMB"],
    "Simiuisonna 12 5":["MD"],
    "Simiuisonna 13 5":["D EQVI"],
    "Simiuisonna 14 5":["N EQVI"],
    "Simiuisonna 15 5":["DSNS EQVI"],
    "Simiuisonna 16 5":["D EQVI"],
    "Simiuisonna 17 5":["D EQVI"],
    "Simiuisonna 18 5":["D AMB EQVI"],
    "Simiuisonna 19 5":["MD"],
    "Simiuisonna 20 5":["D AMB"],
    "Simiuisonna 21 5":["ITT D EQVI"],
    "Simiuisonna 22 5":["D AMB"],
    "Simiuisonna 23 5":["MD"],
    "Simiuisonna 24 5":["D AMB"],
    "Simiuisonna 25 5":["MD"],
    "Simiuisonna 26 5":["D AMB"],
    "Simiuisonna 27 5":["MD"],
    "Simiuisonna 28 5":["D AMB"],
    "Simiuisonna 29 5":["MD"],
    "Simiuisonna 30 5":["D AMB"],
    "Equos 1 5":["D"],
    "Equos 2 5":["PRINI LAG"],
    "Equos 3 5":["N SIMIVIS"],
    "Equos 4 5":["IIT D"],
    "Equos 5 5":["D AMB"],
    "Equos 6 5":["MD SIMIVISO"],
    "Equos 7 5":["D"],
    "Equos 8 5":["PRINI LAG"],
    "Equos 9 5":["ITI D"],
    "Equos 10 5":["IIT D"],
    "Equos 11 5":["D AMB"],
    "Equos 12 5":["D"],
    "Equos 13 5":["MD SIMIV"],
    "Equos 14 5":["MD SIMIV"],
    "Equos 15 5":["N SIMIV"],
    "Equos 16 5":["MD SIMIVIS"],
    "Equos 17 5":["MD SIMIVIS"],
    "Equos 18 5":["D AMB SIMIVIS"],
    "Equos 19 5":["D"],
    "Equos 20 5":["TII D AMB"],
    "Equos 21 5":["IIT MD SIMIVIS"],
    "Equos 22 5":["IIT D AMB"],
    "Equos 23 5":["D"],
    "Equos 24 5":["D AMB"],
    "Equos 25 5":["D"],
    "Equos 26 5":["TII D AMB", "IVOS"],
    "Equos 27 5":["ITI D", "IVOS"],
    "Equos 28 5":["IIT D AMB", "IVOS"],
    "Equos 29 5":["D", "IVOS"],
    "Equos 30 5":["D AMB", "IVOS"],
    "Elembi 1 5":["D", "IVOS"],
    "Elembi 2 5":["D", "IVOS"],
    "Elembi 3 5":["PRINI LAG", "IVOS"],
    "Elembi 4 5":["N", "IVOS"],
    "Elembi 5 5":["IIT D AMB"],
    "Elembi 6 5":["D"],
    "Elembi 7 5":["D"],
    "Elembi 8 5":["D"],
    "Elembi 9 5":["PRINI LAG"],
    "Elembi 10 5":["N INIS R"],
    "Elembi 11 5":["IIT D AMB"],
    "Elembi 12 5":["D"],
    "Elembi 13 5":["D"],
    "Elembi 14 5":["D"],
    "Elembi 15 5":["N"],
    "Elembi 16 5":["N EDRIN"],
    "Elembi 17 5":["MD EDRIN"],
    "Elembi 18 5":["D EDRIN AMB"],
    "Elembi 19 5":["D"],
    "Elembi 20 5":["D AMB"],
    "Elembi 21 5":["TIT D"],
    "Elembi 22 5":["ITI D AMB"],
    "Elembi 23 5":["IIT D"],
    "Elembi 24 5":["D AMB"],
    "Elembi 25 5":["D"],
    "Elembi 26 5":["D AMB"],
    "Elembi 27 5":["TII D"],
    "Elembi 28 5":["ITI D AMB"],
    "Elembi 29 5":["IIT D"],
    "Aedrinni 1 5":["D CANTLI", "IVOS"],
    "Aedrinni 2 5":["MD", "IVOS"],
    "Aedrinni 3 5":["MD", "IVOS"],
    "Aedrinni 4 5":["MD"],
    "Aedrinni 5 5":["N"],
    "Aedrinni 6 5":["PRINI LOUD"],
    "Aedrinni 7 5":["MD [TIOGBR?]"],
    "Aedrinni 8 5":["MD TIOCOBREXTIO"],
    "Aedrinni 9 5":["MD"],
    "Aedrinni 10 5":["MD"],
    "Aedrinni 11 5":["D AMB"],
    "Aedrinni 12 5":["MD"],
    "Aedrinni 13 5":["MD"],
    "Aedrinni 14 5":["MD"],
    "Aedrinni 15 5":["MD"],
    "Aedrinni 16 5":["D ELEMB"],
    "Aedrinni 17 5":["N ELEMB"],
    "Aedrinni 18 5":["D ELEMB AMB"],
    "Aedrinni 19 5":["MD"],
    "Aedrinni 20 5":["D AMB"],
    "Aedrinni 21 5":["IIT MD"],
    "Aedrinni 22 5":["D AMB"],
    "Aedrinni 23 5":["MD"],
    "Aedrinni 24 5":["D AMB"],
    "Aedrinni 25 5":["MD SINDIV IVOS"],
    "Aedrinni 26 5":["D AMB"],
    "Aedrinni 27 5":["MD"],
    "Aedrinni 28 5":["D AMB"],
    "Aedrinni 29 5":["MD"],
    "Aedrinni 30 5":["N"],
    "Cantlos 1 5":["MD AEDRIN"],
    "Cantlos 2 5":["D"],
    "Cantlos 3 5":["D"],
    "Cantlos 4 5":["PRINI LAG"],
    "Cantlos 5 5":["ITI D AMB"],
    "Cantlos 6 5":["N"],
    "Cantlos 7 5":["D"],
    "Cantlos 8 5":["D"],
    "Cantlos 9 5":["D"],
    "Cantlos 10 5":["TII D"],
    "Cantlos 11 5":["ITI D AMB"],
    "Cantlos 12 5":["IIT D"],
    "Cantlos 13 5":["D"],
    "Cantlos 14 5":["D"],
    "Cantlos 15 5":["D TIOCOBREXTIO"],
    "Cantlos 16 5":["TII D"],
    "Cantlos 17 5":["ITI D"],
    "Cantlos 18 5":["N"],
    "Cantlos 19 5":["N INIS R"],
    "Cantlos 20 5":["D AMB"],
    "Cantlos 21 5":["IIT D"],
    "Cantlos 22 5":["TII D AMB"],
    "Cantlos 23 5":["ITI D"],
    "Cantlos 24 5":["IIT D AMB"],
    "Cantlos 25 5":["D"],
    "Cantlos 26 5":["D AMB"],
    "Cantlos 27 5":["D"],
    "Cantlos 28 5":["TII D AMB", "IVOS"],
    "Cantlos 29 5":["(ITI) D", "IVOS"]
  }
  return inscrips[this.string(true)];
}

colignyDate.prototype.calcDays = function(add) {
  var output = new colignyDate(this.year, this.month.index, this.day,
               this.metonic);

  output.day += add;

  while (output.day > output.month.days) {
    if (output.month.index === output.fullYear.months.length - 1) {
      output = new colignyDate(output.year + 1, 0, 
               output.day - output.month.days, output.metonic);
    } else {
      output = new colignyDate(output.year, output.month.index + 1, 
               output.day - output.month.days, output.metonic);
    }
  }

  while (output.day < 1) {
    if (output.month.index === 0) {
      var newLength = new colignyYear(output.year - 1,
                      output.metonic).months.length;
      output = new colignyDate(output.year - 1, newLength - 1, 
               output.day + output.month.days, output.metonic);
    } else {
      output = new colignyDate(output.year, output.months.index - 1,
               output.day + output.month.days, output.metonic);
    }
  }

  return output;  
}

colignyDate.prototype.equals = function(target) {
  if (this.metonic !== target.metonic) {
    throw _colignyErrors["invalidCycles"];
  }

  if (this.year === target.year &&
      this.month.index === target.month.index &&
      this.day === target.day) {
    return true;
  } else {
    return false;
  }
}

colignyDate.prototype.before = function(target) {
  if (this.metonic !== target.metonic) {
    throw _colignyErrors["invalidCycles"];
  }

  if (this.equals(target)) {
    return false;
  } else if (this.year > target.year) {
    return false;
  } else if (this.year < target.year) {
    return true;
  } else if (this.month.index > target.month.index) {
    return false;
  } else if (this.month.index < target.month.index) {
    return true;
  } else if (this.day < target.day) {
    return true;
  } else {
    return false;
  }
}

colignyDate.prototype.difference = function(target) {
  if (this.metonic !== target.metonic) {
    throw _colignyErrors["invalidCycles"];
  }

  var count = 0;

  if (this.equals(target)) {
    return 0;
  } else if (this.year === target.year &&
             this.month.index === target.month.index) {
    return Math.abs(this.day - target.day);
  } else if (target.before(this)) {
    return target.difference(this);
  } else {
    if (this.year === target.year) {
      count += this.month.days - this.day + target.day;
      for (i = this.month.index + 1; i < target.month.index; i++) {
        count += this.fullYear.months[i].days;
      }
    } else {
      count += this.yearToEnd + target.yearToBegin;
      for (var i = this.year + 1; i < target.year; i++) {
        var current = new colignyYear(i, this.metonic);
        count += current.yearDays;
      }
    }
  }
  return count;
}

colignyDate.prototype.toGregorianDate = function() {
  if (this.metonic) {
    var start = new colignyDate(4999, 0, 1, true);
    var gregDate = new Date(1999, 4, 22);
  } else {
    var start = new colignyDate(4998, 0, 1);
    var gregDate = new Date(1998, 4, 3);
  }

  var change = this.difference(start);
  var output = new Date(gregDate);

  if (this.before(start)) {
    output.setDate(output.getDate() - change);
  } else {
    output.setDate(output.getDate() + change);
  }

  return output;
}








